<?php
declare(strict_types=1);

use Migrations\AbstractSeed;

/**
 * Subjects seed.
 */
class SubjectsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run(): void
    {
        $data = [
            [
                'id' => 1,
                'code' => '011',
                'name' => 'CIVICS',
                'short_name' => 'CIV',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 2,
                'code' => '012',
                'name' => 'HISTORY',
                'short_name' => 'HIST',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 3,
                'code' => '013',
                'name' => 'GEOGRAPHY',
                'short_name' => 'GEO',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 4,
                'code' => '014',
                'name' => 'BIBLE KNOWLEDGE',
                'short_name' => 'B/KNOWL',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 5,
                'code' => '015',
                'name' => 'ELIMU YA DINI YA KIISLAMU',
                'short_name' => 'E/D/KIISLAMU',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 6,
                'code' => '016',
                'name' => 'FINE ART',
                'short_name' => 'F.ART',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 7,
                'code' => '017',
                'name' => 'MUSIC',
                'short_name' => 'MUSIC',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 8,
                'code' => '018',
                'name' => 'PHYSICAL EDUCATION',
                'short_name' => 'PHY EDU',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 9,
                'code' => '021',
                'name' => 'KISWAHILI',
                'short_name' => 'KISWAHILI',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 10,
                'code' => '022',
                'name' => 'ENGLISH LANGUAGE',
                'short_name' => 'ENGL',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 11,
                'code' => '023',
                'name' => 'FRENCH LANGUAGE ',
                'short_name' => 'FREN',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 12,
                'code' => '024',
                'name' => 'LITERATURE IN ENGLISH',
                'short_name' => 'LIT ENG',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 13,
                'code' => '025',
                'name' => 'ARABIC LANGUAGE',
                'short_name' => 'ARABIC LANGUAGE',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 14,
                'code' => '031',
                'name' => 'PHYSICS',
                'short_name' => 'PHY',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 15,
                'code' => '032',
                'name' => 'CHEMISTRY',
                'short_name' => 'CHEM',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 16,
                'code' => '033',
                'name' => 'BIOLOGY',
                'short_name' => 'BIO',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 17,
                'code' => '0134',
                'name' => 'AGRICULTURAL SCIENCE',
                'short_name' => 'AGRI',
                'description' => 'AGRICULTURAL SCIENCE',
                'exam_types_id' => 1,
            ],
            [
                'id' => 18,
                'code' => '035',
                'name' => 'ENGINEERING SCIENCE',
                'short_name' => 'ENG SC',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 19,
                'code' => '036',
                'name' => 'INFORMATION & COMPUTER STUDIES',
                'short_name' => 'COMP STUD',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 20,
                'code' => '041',
                'name' => 'BASIC MATHEMATICS',
                'short_name' => 'B/MATH',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 21,
                'code' => '042',
                'name' => 'ADDITIONAL MATHEMATICS',
                'short_name' => 'ADD MATH',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 22,
                'code' => '051',
                'name' => 'FOOD & NUTRITION',
                'short_name' => 'FOOD',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 23,
                'code' => '052',
                'name' => 'TEXTILE & DRESSMAKING',
                'short_name' => 'TEXTILE',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 24,
                'code' => '061',
                'name' => 'COMMERCE',
                'short_name' => 'COMM',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 25,
                'code' => '062',
                'name' => 'BOOK-KEEPING',
                'short_name' => 'B/KEEPING',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 26,
                'code' => '063',
                'name' => 'TYPEWRITING',
                'short_name' => 'TYPEWRITING',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 27,
                'code' => '071',
                'name' => 'BUILDING CONSTRUCTION',
                'short_name' => 'BLD CONSTR',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 28,
                'code' => '072',
                'name' => 'ARCHTECTURAL DRAUGHTING',
                'short_name' => 'ARCH DRAUGHT',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 29,
                'code' => '073',
                'name' => 'SURVEYING',
                'short_name' => 'SURVEYING',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 30,
                'code' => '074',
                'name' => 'CARPENTRY & JOINERY',
                'short_name' => 'CARP & JOIN',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 31,
                'code' => '075',
                'name' => 'BRICKWORK & MASONRY',
                'short_name' => 'BRI & MAS',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 32,
                'code' => '076',
                'name' => 'PAINTING & SIGN WRITING',
                'short_name' => 'PAINT & SIGN',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 33,
                'code' => '077',
                'name' => 'PLUMBING',
                'short_name' => 'PLUMBING',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 34,
                'code' => '081',
                'name' => 'ELECTRICAL INSTALLATION',
                'short_name' => 'ELECT INST',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 35,
                'code' => '082',
                'name' => 'ELECTRICAL ENGINEERING SCIENCE',
                'short_name' => 'ELECT ENG SC',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 36,
                'code' => '083',
                'name' => 'RADIO & TV SERVICING',
                'short_name' => 'RADIO & TV',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 37,
                'code' => '084',
                'name' => 'ELECTRICAL DRAUGHTING',
                'short_name' => 'ELECT DRAUGHT',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 38,
                'code' => '085',
                'name' => 'REFRIGERATION & AIR CONDITION',
                'short_name' => 'REFRIG & AIR COND',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 39,
                'code' => '092',
                'name' => 'WORKSHOP TECHNOLOGY',
                'short_name' => 'W/SHOP TECH',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 40,
                'code' => '093',
                'name' => 'MOTOR VEHICLE MECHANICS',
                'short_name' => 'MOT VEH MECH',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 41,
                'code' => '094',
                'name' => 'WELDING & METAL FABRICATION',
                'short_name' => 'WELD & MET ',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 42,
                'code' => '095',
                'name' => 'FITTING & TURNING',
                'short_name' => 'FITT & TURN',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 43,
                'code' => '096',
                'name' => 'AUTO ELECTRICS',
                'short_name' => 'AUTO ELECT',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 44,
                'code' => '097',
                'name' => 'MECHANICAL DRAUGHTING',
                'short_name' => 'MECH DRAUGHT',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 45,
                'code' => '086',
                'name' => 'PLANT & EQUIPMENT MAINTANANCE',
                'short_name' => 'PL & EQUIP MAINT',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 46,
                'code' => '091',
                'name' => 'TECHINICAL DRAWING',
                'short_name' => 'TECH DRAWING',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 47,
                'code' => '010',
                'name' => 'QUALIFYING TEST',
                'short_name' => 'QUALIFYING TEST',
                'description' => NULL,
                'exam_types_id' => 3,
            ],
            [
                'id' => 48,
                'code' => '111',
                'name' => 'GENERAL STUDIES',
                'short_name' => 'G/STUDIES',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 49,
                'code' => '112',
                'name' => 'HISTORY',
                'short_name' => 'HISTORY',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 50,
                'code' => '113',
                'name' => 'GEOGRAPHY',
                'short_name' => 'GEOGR',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 51,
                'code' => '114',
                'name' => 'DIVINITY',
                'short_name' => 'DIVINITY',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 52,
                'code' => '115',
                'name' => 'ISLAMIC KNOWLEDGE',
                'short_name' => 'IS/KNOWLEDGE',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 53,
                'code' => '121',
                'name' => 'KISWAHILI',
                'short_name' => 'KISWAHILI',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 54,
                'code' => '122',
                'name' => 'ENGLISH LANGUAGE',
                'short_name' => 'ENGLISH',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 55,
                'code' => '123',
                'name' => 'FRENCH',
                'short_name' => 'FRENCH',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 56,
                'code' => '125',
                'name' => 'ARABIC',
                'short_name' => 'ARABIC',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 57,
                'code' => '131',
                'name' => 'PHYSICS',
                'short_name' => 'PHYSICS',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 58,
                'code' => '132',
                'name' => 'CHEMISTRY',
                'short_name' => 'CHEMISTRY',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 59,
                'code' => '133',
                'name' => 'BIOLOGY',
                'short_name' => 'BIOLOGY',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 60,
                'code' => '134',
                'name' => 'AGRICULTURE',
                'short_name' => 'AGRICULTURE',
                'description' => 'AGRICULTURE',
                'exam_types_id' => 2,
            ],
            [
                'id' => 61,
                'code' => '136',
                'name' => 'COMPUTER SCIENCE',
                'short_name' => 'COMP/SCIENCE',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 62,
                'code' => '141',
                'name' => 'BASIC APPLIED MATHEMATICS',
                'short_name' => 'BAM',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 63,
                'code' => '142',
                'name' => 'ADVANCED MATHEMATICS',
                'short_name' => 'ADV/MATHS',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 64,
                'code' => '151',
                'name' => 'ECONOMICS',
                'short_name' => 'ECONOMICS',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 65,
                'code' => '152',
                'name' => 'COMMERCE',
                'short_name' => 'COMMERCE',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 66,
                'code' => '153',
                'name' => 'ACCOUNTANCY',
                'short_name' => 'ACCOUNTANCY',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 67,
                'code' => '155',
                'name' => 'FOOD & NUTRITION',
                'short_name' => 'F & NUTRITION',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 68,
                'code' => '098',
                'name' => 'FOUNDRY & BLACKSMITH',
                'short_name' => 'FOUNDRY & BLACKSMITH',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 69,
                'code' => '611',
                'name' => 'EDUCATION',
                'short_name' => 'EDUCATION',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 70,
                'code' => '612',
                'name' => 'URAIA',
                'short_name' => 'URAIA',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 71,
                'code' => '613',
                'name' => 'CIVICS',
                'short_name' => 'CIVICS',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 72,
                'code' => '615',
                'name' => 'SOCIAL STUDIES',
                'short_name' => 'SOCIAL STUDIES',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 73,
                'code' => '621',
                'name' => 'KISWAHILI',
                'short_name' => 'KISWAHILI',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 74,
                'code' => '622',
                'name' => 'ENGLISH LANGUAGE',
                'short_name' => 'ENGLISH LANGUAGE',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 75,
                'code' => '630',
                'name' => 'MBINU ZA KUFUNDISHIA SAYANSI',
                'short_name' => 'MBINU ZA KUFUNDISHIA SAYANSI',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 76,
                'code' => '631',
                'name' => 'SCIENCE',
                'short_name' => 'SCIENCE',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 77,
                'code' => '636',
                'name' => 'TEHAMA',
                'short_name' => 'TEHAMA',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 78,
                'code' => '640',
                'name' => 'HISABATI',
                'short_name' => 'HISABATI',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 79,
                'code' => '641',
                'name' => 'MATHEMATICS',
                'short_name' => 'MATHEMATICS',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 80,
                'code' => '649',
                'name' => 'SAYANSI KIMU UFUNDISHAJI',
                'short_name' => 'SAYANSI KIMU UFUNDISHAJI',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 81,
                'code' => '650',
                'name' => 'HAIBA NA MICHEZO',
                'short_name' => 'HAIBA NA MICHEZO',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 82,
                'code' => '652',
                'name' => 'ELIMU KWA MICHEZO',
                'short_name' => 'ELIMU KWA MICHEZO',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 83,
                'code' => '653',
                'name' => 'PHYSICAL EDUCATION',
                'short_name' => 'PHYSICAL EDUCATION',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 84,
                'code' => '654',
                'name' => 'UALIMU KWA MICHEZO',
                'short_name' => 'UALIMU KWA MICHEZO',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 85,
                'code' => '655',
                'name' => 'EDUC.PSYCHOLOGY GUID.&COUNSELL',
                'short_name' => 'EDUC.PSYCHOLOGY GUID.&COUNSELL',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 86,
                'code' => '651',
                'name' => 'PESONALITY AND SPORTS',
                'short_name' => 'PESONALITY AND SPORTS',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 87,
                'code' => '610',
                'name' => 'UALIMU',
                'short_name' => 'UALIMU',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 88,
                'code' => '661',
                'name' => 'GENERAL COURSE',
                'short_name' => 'GENERAL COURSE',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 89,
                'code' => '662',
                'name' => 'V.I: BRAILLE SKILLS: LANGUAGE',
                'short_name' => 'V.I: BRAILLE SKILLS: LANGUAGE',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 90,
                'code' => '663',
                'name' => 'V.I: BRAILLE SKILLS: MATHEMATICAL NOTATION',
                'short_name' => 'V.I: BRAILLE SKILLS: MATHEMATICAL NOTATION',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 91,
                'code' => '664',
                'name' => 'V.I: ORIENTATION AND MOBILITY',
                'short_name' => 'V.I: ORIENTATION AND MOBILITY',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 92,
                'code' => '665',
                'name' => 'V.I: TEACHING METHODOLOGY ',
                'short_name' => 'V.I: TEACHING METHODOLOGY ',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 93,
                'code' => '666',
                'name' => 'V.I: PHYSICAL EDUCATION & DEAFBLINDNESS ',
                'short_name' => 'V.I: PHYSICAL EDUCATION & DEAFBLINDNESS ',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 94,
                'code' => '667',
                'name' => 'V.I: PSYCHOLOGY & DEAFBLINDNESS',
                'short_name' => 'V.I: PSYCHOLOGY & DEAFBLINDNESS',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 95,
                'code' => '668',
                'name' => 'V.I: METHODOLOGY',
                'short_name' => 'V.I.METHODOLOGY',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 96,
                'code' => '669',
                'name' => 'H.I: AUDIOLOGY',
                'short_name' => 'H.I: AUDIOLOGY',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 97,
                'code' => '670',
                'name' => 'H.I: TEACHING METHODOLOGY',
                'short_name' => 'H.I: TEACHING METHODOLOGY',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 98,
                'code' => '671',
                'name' => 'H.I: PHYSICAL EDUCATION',
                'short_name' => 'H.I: PHYSICAL EDUCATION',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 99,
                'code' => '672',
                'name' => 'H.I: COMM/LANG.& SPEECH DEVELOPMENT',
                'short_name' => 'H.I: COMM/LANG.& SPEECH DEVELOPMENT',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 100,
                'code' => '673',
                'name' => 'H.I: SIGN LANGUAGE',
                'short_name' => 'H.I: SIGN LANGUAGE',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 101,
                'code' => '674',
                'name' => 'H.I: HEARING IMPAIRMENT ',
                'short_name' => 'H.I: HEARING IMPAIRMENT ',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 102,
                'code' => '675',
                'name' => 'I.I: PSYCHOLOGY AND AUTISM',
                'short_name' => 'I.I: PSYCHOLOGY AND AUTISM',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 103,
                'code' => '676',
                'name' => 'I.I: COMMUNICATION AND AUTISM',
                'short_name' => 'I.I: COMMUNICATION AND AUTISM',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 104,
                'code' => '677',
                'name' => 'I.I: TEACHING METHODOLOGY & AUTISM',
                'short_name' => 'I.I: TEACHING METHODOLOGY & AUTISM',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 105,
                'code' => '678',
                'name' => 'I.I: PHYSICAL EDUCATION AND AUTISM',
                'short_name' => 'I.I: PHYSICAL EDUCATION AND AUTISM',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 106,
                'code' => '679',
                'name' => 'I.I: INTELLECTUAL IMPAIRMENT & AUTISM',
                'short_name' => 'I.I: INTELLECTUAL IMPAIRMENT & AUTISM',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 107,
                'code' => '710',
                'name' => 'CIVICS PEDAGOGY',
                'short_name' => 'CIVICS PEDAGOGY',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 108,
                'code' => '711',
                'name' => 'DEVELOPMENT STUDIES',
                'short_name' => 'DEVELOPMENT STUDIES',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 109,
                'code' => '712',
                'name' => 'HISTORY',
                'short_name' => 'HISTORY',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 110,
                'code' => '713',
                'name' => 'GEOGRAPHY',
                'short_name' => 'GEOGRAPHY',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 111,
                'code' => '715',
                'name' => 'ELIMU YA DINI YA KIISLAMU',
                'short_name' => 'ELIMU YA DINI YA KIISLAMU',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 112,
                'code' => '716',
                'name' => 'FINE ART & CRAFT',
                'short_name' => 'FINE ART & CRAFT',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 113,
                'code' => '718',
                'name' => 'MUSIC TEACHING METHODS',
                'short_name' => 'MUSIC TEACHING METHODS',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 114,
                'code' => '719',
                'name' => 'THEATRE ARTS',
                'short_name' => 'THEATRE ARTS',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 115,
                'code' => '721',
                'name' => 'LUGHA YA KISWAHILI',
                'short_name' => 'LUGHA YA KISWAHILI',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 116,
                'code' => '722',
                'name' => 'ENGLISH LANGUAGE',
                'short_name' => 'ENGLISH LANGUAGE',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 117,
                'code' => '723',
                'name' => 'FRENCH LANGUAGE',
                'short_name' => 'FRENCH LANGUAGE',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 118,
                'code' => '724',
                'name' => 'COMMUNICATION SKILLS',
                'short_name' => 'COMMUNICATION SKILLS',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 119,
                'code' => '725',
                'name' => 'LUGHA YA KIARABU',
                'short_name' => 'LUGHA YA KIARABU',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 120,
                'code' => '726',
                'name' => 'FINE ART & CRAFT TEACHING METHODS',
                'short_name' => 'FINE ART &CRAFTS TEACH METHODS',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 121,
                'code' => '727',
                'name' => 'PHYCL. EDUC. AND SPORT T/METHODS',
                'short_name' => 'PHYCL. EDUC. AND SPORT T/METHD',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 122,
                'code' => '731',
                'name' => 'PHYSICS',
                'short_name' => 'PHYSICS',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 123,
                'code' => '732',
                'name' => 'CHEMISTRY',
                'short_name' => 'CHEMISTRY',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 124,
                'code' => '733',
                'name' => 'BIOLOGY',
                'short_name' => 'BIOLOGY',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 125,
                'code' => '735',
                'name' => 'AGRICULTURE TEACHING METHODS',
                'short_name' => 'AGRICULTURE TEACHING METHODS',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 126,
                'code' => '736',
                'name' => 'PHYSICAL EDUCATION & SPORT',
                'short_name' => 'PHYSICAL EDUCATION & SPORT',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 127,
                'code' => '738',
                'name' => 'INFORMATION & COMM. TECH. (ICT),',
                'short_name' => 'INFORMATION & COMM. TECH. (ICT),',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 128,
                'code' => '740',
                'name' => 'MATHEMATICS',
                'short_name' => 'MATHEMATICS',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 129,
                'code' => '734',
                'name' => 'AGRICULTURE',
                'short_name' => 'AGRICULTURE',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 130,
                'code' => '750',
                'name' => 'EDUCATION MEDIA & TECHNOLOGY',
                'short_name' => 'EDUCATION MEDIA & TECHNOLOGY',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 131,
                'code' => '751',
                'name' => 'COMMERCE TEACHING METHODS',
                'short_name' => 'COMMERCE TEACHING METHODS',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 132,
                'code' => '752',
                'name' => 'BOOK-KEEPING TEACHING METHODS',
                'short_name' => 'BOOK-KEEPING TEACHING METHODS',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 133,
                'code' => '753',
                'name' => 'HOME ECONOMICS',
                'short_name' => 'HOME ECONOMICS',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 134,
                'code' => '754',
                'name' => 'GENERAL COURSE',
                'short_name' => 'GENERAL COURSE',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 135,
                'code' => '755',
                'name' => 'V.I: BRAILLE SKILLS: LANGUAGE',
                'short_name' => 'V.I: BRAILLE SKILLS: LANGUAGE',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 136,
                'code' => '756',
                'name' => 'V.I: BRAILLE SKILLS: MATHEMATICAL NOTATION',
                'short_name' => 'V.I: BRAILLE SKILLS: MATHEMATICAL NOTATION',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 137,
                'code' => '761',
                'name' => 'EDUC. PSYCH. GUIDNS & COUNSEL.',
                'short_name' => 'EDUC. PSYCH. GUIDNS & COUNSEL.',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 138,
                'code' => '762',
                'name' => 'EDUC. RES. MEAS. & EVALUATION',
                'short_name' => 'EDUC. RES. MEAS. & EVALUATION',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 139,
                'code' => '763',
                'name' => 'FOUNDATIONS OF EDUCATION',
                'short_name' => 'FOUNDATIONS OF EDUCATION',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 140,
                'code' => '764',
                'name' => 'CURRICULUM AND TEACHING',
                'short_name' => 'CURRICULUM AND TEACHING',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 141,
                'code' => '766',
                'name' => 'V.I: PSYCHOLOGY & DEAFBLINDNESS',
                'short_name' => 'V.I: PSYCHOLOGY & DEAFBLINDNESS',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 142,
                'code' => '767',
                'name' => 'V.I: ORIENTATION AND MOBILITY & DEAFBLINDNESS',
                'short_name' => 'V.I: ORIENTATION AND MOBILITY & DEAFBLINDNESS',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 143,
                'code' => '768',
                'name' => 'V.I: PHYSICAL EDUCATION & DEAFBLINDNESS',
                'short_name' => 'V.I: PHYSICAL EDUCATION & DEAFBLINDNESS',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 144,
                'code' => '715',
                'name' => 'ELIMU YA DINI YA KIISLAMU',
                'short_name' => 'ELIMU YA DINI YA KIISLAMU',
                'description' => NULL,
                'exam_types_id' => 7,
            ],
            [
                'id' => 145,
                'code' => '741',
                'name' => 'MATHEMATICS',
                'short_name' => 'MATHEMATICS',
                'description' => NULL,
                'exam_types_id' => 7,
            ],
            [
                'id' => 146,
                'code' => '744',
                'name' => 'GENERAL STUDIES',
                'short_name' => 'GENERAL STUDIES',
                'description' => NULL,
                'exam_types_id' => 7,
            ],
            [
                'id' => 147,
                'code' => '772',
                'name' => 'EDUCATION',
                'short_name' => 'EDUCATION',
                'description' => NULL,
                'exam_types_id' => 7,
            ],
            [
                'id' => 148,
                'code' => '781',
                'name' => 'ENGINEERING SCIENCE',
                'short_name' => 'ENGINEERING SCIENCE',
                'description' => NULL,
                'exam_types_id' => 7,
            ],
            [
                'id' => 149,
                'code' => '782',
                'name' => 'ARCHITECTURAL DRAWING',
                'short_name' => 'ARCHITECTURAL DRAWING',
                'description' => NULL,
                'exam_types_id' => 7,
            ],
            [
                'id' => 150,
                'code' => '783',
                'name' => 'BUILDING CONSTRUCTION',
                'short_name' => 'BUILDING CONSTRUCTION',
                'description' => NULL,
                'exam_types_id' => 7,
            ],
            [
                'id' => 151,
                'code' => '784',
                'name' => 'BRICKWORK & MASONRY',
                'short_name' => 'BRICKWORK & MASONRY',
                'description' => NULL,
                'exam_types_id' => 7,
            ],
            [
                'id' => 152,
                'code' => '788',
                'name' => 'TECHNICAL DRAWING',
                'short_name' => 'TECHNICAL DRAWING',
                'description' => NULL,
                'exam_types_id' => 7,
            ],
            [
                'id' => 153,
                'code' => '789',
                'name' => 'METALWORK & MECH PRACT.',
                'short_name' => 'METALWORK & MECH PRACT.',
                'description' => NULL,
                'exam_types_id' => 7,
            ],
            [
                'id' => 154,
                'code' => '790',
                'name' => 'AUTOMOBILE TECHNOLOGY',
                'short_name' => 'AUTOMOBILE TECHNOLOGY',
                'description' => NULL,
                'exam_types_id' => 7,
            ],
            [
                'id' => 155,
                'code' => '792',
                'name' => 'WELDING & FABRICATION',
                'short_name' => 'WELDING & FABRICATION',
                'description' => NULL,
                'exam_types_id' => 7,
            ],
            [
                'id' => 156,
                'code' => '793',
                'name' => 'ELECTRONICS',
                'short_name' => 'ELECTRONICS',
                'description' => NULL,
                'exam_types_id' => 7,
            ],
            [
                'id' => 157,
                'code' => '794',
                'name' => 'ELECTRICAL INSTALLATION',
                'short_name' => 'ELECTRICAL INSTALLATION',
                'description' => NULL,
                'exam_types_id' => 7,
            ],
            [
                'id' => 158,
                'code' => '795',
                'name' => 'ELECTRICAL DRAWING',
                'short_name' => 'ELECTRICAL DRAWING',
                'description' => NULL,
                'exam_types_id' => 7,
            ],
            [
                'id' => 159,
                'code' => '0',
                'name' => 'BTP',
                'short_name' => 'BTP',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 160,
                'code' => '0',
                'name' => 'BTP',
                'short_name' => 'BTP',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 161,
                'code' => '0',
                'name' => 'BTP',
                'short_name' => 'BTP',
                'description' => NULL,
                'exam_types_id' => 7,
            ],
            [
                'id' => 162,
                'code' => '019',
                'name' => 'THEATRE ART',
                'short_name' => 'THEATRE ART',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 163,
                'code' => '011',
                'name' => 'CIVICS',
                'short_name' => 'CIVICS',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 164,
                'code' => '012',
                'name' => 'HISTORY',
                'short_name' => 'HISTORY',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 165,
                'code' => '013',
                'name' => 'GEOGRAPHY',
                'short_name' => 'GEOGRAPHY',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 166,
                'code' => '014',
                'name' => 'BIBLE KNOWLEDGE',
                'short_name' => 'BIBLE KNOWLEDGE',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 167,
                'code' => '015',
                'name' => 'ELIMU YA DINI YA KIISLAMU',
                'short_name' => 'ELIMU YA DINI YA KIISLAMU',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 168,
                'code' => '016',
                'name' => 'FINE ARTS',
                'short_name' => 'FINE ARTS',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 169,
                'code' => '017',
                'name' => 'MUSIC',
                'short_name' => 'MUSIC',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 170,
                'code' => '018',
                'name' => 'PHYSICAL EDUCATION',
                'short_name' => 'PHYSICAL EDUCATION',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 171,
                'code' => '019',
                'name' => 'THEATRE ARTS',
                'short_name' => 'THEATRE ARTS',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 172,
                'code' => '021',
                'name' => 'KISWAHILI',
                'short_name' => 'KISWAHILI',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 173,
                'code' => '022',
                'name' => 'ENGLISH LANGUAGE',
                'short_name' => 'ENGLISH LANGUAGE',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 174,
                'code' => '023',
                'name' => 'FRENCH LANGUAGE',
                'short_name' => 'FRENCH LANGUAGE',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 175,
                'code' => '025',
                'name' => 'ARABIC LANGUAGE',
                'short_name' => 'ARABIC LANGUAGE',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 176,
                'code' => '026',
                'name' => 'CHINESE',
                'short_name' => 'CHINESE',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 177,
                'code' => '031',
                'name' => 'PHYSICS',
                'short_name' => 'PHYSICS',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 178,
                'code' => '032',
                'name' => 'CHEMISTRY',
                'short_name' => 'CHEMISTRY',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 179,
                'code' => '033',
                'name' => 'BIOLOGY',
                'short_name' => 'BIOLOGY',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 180,
                'code' => '034',
                'name' => 'AGRICULTURE SCIENCE',
                'short_name' => 'AGRICULTURE SCIENCE',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 181,
                'code' => '035',
                'name' => 'ENGINEERING SCIENCE',
                'short_name' => 'ENGINEERING SCIENCE',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 182,
                'code' => '036',
                'name' => 'INFORMATION & COMPUTER STUDIES',
                'short_name' => 'INFORM. & COMP. STUDIES',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 183,
                'code' => '041',
                'name' => 'BASIC MATHEMATICS',
                'short_name' => 'BASIC MATHEMATICS',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 184,
                'code' => '042',
                'name' => 'ADDITIONAL MATHEMATICS',
                'short_name' => 'ADDITIONAL MATHEMATICS',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 185,
                'code' => '051',
                'name' => 'FOOD & NUTRITION',
                'short_name' => 'FOOD & NUTRITION',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 186,
                'code' => '052',
                'name' => 'TEXTILES & DRESSMAKING',
                'short_name' => 'TEXTILES & DRESSMAKING',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 187,
                'code' => '061',
                'name' => 'COMMERCE',
                'short_name' => 'COMMERCE',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 188,
                'code' => '062',
                'name' => 'BOOK KEEPING',
                'short_name' => 'BOOK KEEPING',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 189,
                'code' => '063',
                'name' => 'TYPEWRITING',
                'short_name' => 'TYPEWRITING',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 190,
                'code' => '070',
                'name' => 'TECHNICAL DRAWING',
                'short_name' => 'TECHNICAL DRAWING',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 191,
                'code' => '071',
                'name' => 'CIVIL ENGINEERING',
                'short_name' => 'CIVIL ENGINEERING',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 192,
                'code' => '080',
                'name' => 'ELECTRICAL ENGINEERING',
                'short_name' => 'ELECTRICAL ENGINEERING',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 193,
                'code' => '090',
                'name' => 'MECHANICAL ENGINEERING',
                'short_name' => 'MECHANICAL ENGINEERING',
                'description' => NULL,
                'exam_types_id' => 9,
            ],
            [
                'id' => 194,
                'code' => '026',
                'name' => 'CHINESE LANGUANGE',
                'short_name' => 'CHINESE ',
                'description' => NULL,
                'exam_types_id' => 1,
            ],
            [
                'id' => 195,
                'code' => '614',
                'name' => 'MAARIFA YA JAMII',
                'short_name' => 'MAARIFA YA JAMII',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 196,
                'code' => '616',
                'name' => 'ELIMU YA DINI YA KIISLAMU',
                'short_name' => 'ELIMU YA DINI YA KIISLAMU',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 197,
                'code' => '624',
                'name' => 'COMMUNICATION SKILLS',
                'short_name' => 'COMMUNICATION SKILLS',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 198,
                'code' => '632',
                'name' => 'SAYANSI',
                'short_name' => 'SAYANSI',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 199,
                'code' => '633',
                'name' => 'VOCATIONAL SKILLS',
                'short_name' => 'VOCATIONAL SKILLS',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 200,
                'code' => '634',
                'name' => 'STADI ZA KAZI',
                'short_name' => 'STADI ZA KAZI',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 201,
                'code' => '635',
                'name' => 'INFORMATION & COMM. TECH. (ICT),',
                'short_name' => 'INFORMATION & COMM. TECH. (ICT),',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 202,
                'code' => '638',
                'name' => 'VIELELEZO NA TEKNOLOJIA',
                'short_name' => 'VIELELEZO NA TEKNOLOJIA',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 203,
                'code' => '680',
                'name' => 'UALIMU ELIMU YA AWALI',
                'short_name' => 'UALIMU ELIMU YA AWALI',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 204,
                'code' => '682',
                'name' => 'VITENDO VYA KUJIFUNZA HISABATI',
                'short_name' => 'VITENDO VYA KUJIFUNZA HISABATI',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 205,
                'code' => '683',
                'name' => 'MATHEMATICS LERNING ACTIVITIES',
                'short_name' => 'MATHEMATICS LERNING ACTIVITIES',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 206,
                'code' => '684',
                'name' => 'VITENDO VYA KUJIFUNZA SANAA',
                'short_name' => 'VITENDO VYA KUJIFUNZA SANAA',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 207,
                'code' => '685',
                'name' => 'ARTS LERNING ACTIVITIES',
                'short_name' => 'ARTS LERNING ACTIVITIES',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 208,
                'code' => '686',
                'name' => 'VITENDO VYA KUJIFUNZA KISWAHILI',
                'short_name' => 'VITENDO VYA KUJIFUNZA KISWAHILI',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 209,
                'code' => '687',
                'name' => 'VITENDO VYA KUJIFUNZA HAIBA NA MICHEZO',
                'short_name' => 'VITENDO VYA KUJIFUNZA HAIBA NA MICHEZO',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 210,
                'code' => '688',
                'name' => 'PERSONALITY AND SPORTS LERNING ACTIVITIES',
                'short_name' => 'PERSONALITY AND SPORTS LERNING ACTIVITIES',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 211,
                'code' => '689',
                'name' => 'VITENDO VYA KUJIFUNZA SAYANSI',
                'short_name' => 'VITENDO VYA KUJIFUNZA SAYANSI',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 212,
                'code' => '690',
                'name' => 'SCIENCE LERNING ACTIVITIES',
                'short_name' => 'SCIENCE LERNING ACTIVITIES',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 213,
                'code' => '691',
                'name' => 'ENGLISH LANGUAGE LEARNING ACTIVITIES',
                'short_name' => 'ENGLISH LANGUAGE LEARNING ACTIVITIES',
                'description' => NULL,
                'exam_types_id' => 4,
            ],
            [
                'id' => 214,
                'code' => '737',
                'name' => 'COMPUTER SCIENCE',
                'short_name' => 'COMPUTER SCIENCE',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 215,
                'code' => '758',
                'name' => 'V.I: TEACHING METHODOLOGY & DEAFBLINDNESS ',
                'short_name' => 'V.I: TEACHING METHODOLOGY & DEAFBLINDNESS ',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 216,
                'code' => '161',
                'name' => 'EDUCATION',
                'short_name' => 'EDUCATION',
                'description' => NULL,
                'exam_types_id' => 2,
            ],
            [
                'id' => 217,
                'code' => '635',
                'name' => 'INFORMATION & COMM. TECH. (ICT),',
                'short_name' => 'INFORMATION & COMM. TECH. (ICT)',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 218,
                'code' => '624',
                'name' => 'COMMUNICATION SKILLS',
                'short_name' => 'COMMUNICATION SKILLS',
                'description' => NULL,
                'exam_types_id' => 5,
            ],
            [
                'id' => 219,
                'code' => '769',
                'name' => 'H.I: AUDIOLOGY',
                'short_name' => 'H.I: AUDIOLOGY',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 220,
                'code' => '770',
                'name' => 'H.I: HEARING IMPAIRMENT  AND EAR',
                'short_name' => 'H.I: HEARING IMPAIRMENT  AND EAR',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 221,
                'code' => '771',
                'name' => 'H.I:TEACHING METHODOLOGY',
                'short_name' => 'H.I:TEACHING METHODOLOGY',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 222,
                'code' => '773',
                'name' => 'H.I: PHYSICAL EDUCATION',
                'short_name' => 'H.I: PHYSICAL EDUCATION',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 223,
                'code' => '779',
                'name' => 'I.I: SIGN LANGUAGE',
                'short_name' => 'I.I: SIGN LANGUAGE',
                'description' => NULL,
                'exam_types_id' => 6,
            ],
            [
                'id' => 224,
                'code' => '001',
                'name' => 'KISWAHILI',
                'short_name' => 'KISWAHILI',
                'description' => 'KISWAHILI',
                'exam_types_id' => 11,
            ],
            [
                'id' => 225,
                'code' => '002',
                'name' => 'ENGLISH LANGUAGE',
                'short_name' => 'ENGLISH LANGUAGE',
                'description' => 'ENGLISH LANGUAGE',
                'exam_types_id' => 11,
            ],
            [
                'id' => 226,
                'code' => '003',
                'name' => 'MAARIFA YA JAMII',
                'short_name' => 'MAARIFA YA JAMII',
                'description' => 'MAARIFA YA JAMII',
                'exam_types_id' => 11,
            ],
            [
                'id' => 227,
                'code' => '003E',
                'name' => 'SOCIAL STUDIES',
                'short_name' => 'SOCIAL STUDIES',
                'description' => 'SOCIAL STUDIES',
                'exam_types_id' => 11,
            ],
            [
                'id' => 228,
                'code' => '004',
                'name' => 'HISABATI',
                'short_name' => 'HISABATI',
                'description' => 'HISABATI',
                'exam_types_id' => 11,
            ],
            [
                'id' => 229,
                'code' => '004E',
                'name' => 'MATHEMATICS',
                'short_name' => 'MATHEMATICS',
                'description' => 'MATHEMATICS',
                'exam_types_id' => 11,
            ],
            [
                'id' => 230,
                'code' => '005',
                'name' => 'SAYANSI NA TEKNOLOJIA',
                'short_name' => 'SAYANSI NA TEKNOLOJIA',
                'description' => 'SAYANSI NA TEKNOLOJIA',
                'exam_types_id' => 11,
            ],
            [
                'id' => 231,
                'code' => '005E',
                'name' => 'SCIENCE AND TECHNOLOGY',
                'short_name' => 'SCIENCE AND TECHNOLOGY',
                'description' => 'SCIENCE AND TECHNOLOGY',
                'exam_types_id' => 11,
            ],
            [
                'id' => 232,
                'code' => '006',
                'name' => 'URAIA NA MAADILI',
                'short_name' => 'URAIA NA MAADILI',
                'description' => 'URAIA NA MAADILI',
                'exam_types_id' => 11,
            ],
            [
                'id' => 233,
                'code' => '006E',
                'name' => 'CIVIC AND MORAL EDUCATION',
                'short_name' => 'CIVIC AND MORAL EDUCATION',
                'description' => 'CIVIC AND MORAL EDUCATION',
                'exam_types_id' => 11,
            ],
            [
                'id' => 234,
                'code' => '134',
                'name' => 'AGRICULTURE',
                'short_name' => 'AGRICULTURE',
                'description' => 'AGRICULTURE',
                'exam_types_id' => 24,
            ],
        ];

        $table = $this->table('subjects');
        $table->insert($data)->save();
    }
}
